from typing import Literal
import enum
import io
import os
import pathlib
import re
import urllib.request
import zipfile
import os.path
import textwrap
from dataclasses import dataclass

OPENCL_ICD_LOADER_ZIP_URL = "https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/refs/tags/v2026.05.29.zip"
OPENCL_HEADERS_ZIP_URL = "https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/tags/v2026.05.29.zip"

OPENCL_ICD_LOADER_INCLUDE_RE = r"^OpenCL-ICD-Loader-[^/]+/(loader|include)/.+\.[ch]$"
OPENCL_ICD_LOADER_EXCLUDE_RE = r".+/cllayerinfo\.c$"
OPENCL_ICD_LOADER_PRELUDES = [
    (r".+/loader/windows/.+\.[ch]$", "//go:build windows\n\n"),
    (r".+/loader/linux/.+\.[ch]$", "//go:build linux\n\n"),
]
OPENCL_ICD_LOADER_EXTRA_FILES = [
    ("icd_cmake_config.h", "#define HAVE_SECURE_GETENV\n#define HAVE___SECURE_GETENV"),
]

OPENCL_HEADERS_INCLUDE_RE = r"^OpenCL-Headers-[^/]+/CL/.+\.[h]$"
OPENCL_HEADERS_REPLACEMENTS = [
    (r"^.+/cl.h$", r"^#if defined\(CL_VERSION_2_0\) && __CL_HAS_ANON_UNION__\n([^#]*\n)+#endif\n", ""),
]

GO_PRELUDE = """// Code generated by generate.py; DO NOT EDIT.
package cl

/*
#cgo CFLAGS: -DCL_TARGET_OPENCL_VERSION=310
#cgo CFLAGS: -DCL_NO_NON_ICD_DISPATCH_EXTENSION_PROTOTYPES
#cgo CFLAGS: -DCL_ENABLE_LAYERS
#cgo CFLAGS: -Wno-deprecated-declarations
#cgo CFLAGS: -Iinc/
#cgo windows LDFLAGS: -lcfgmgr32 -lruntimeobject -lOle32
#include "inc/CL/cl.h"
#include "cl.go.h"
*/
import "C"

import (
    "fmt"
    "runtime"
    "slices"
    "sync"
    "unsafe"
)

// Custom utilities
func boolToClBool(b bool) C.cl_bool {
    if b {
        return 1
    } else {
        return 0
    }
}
func cstringToString(cstr *C.char) string {
    s := (*[1<<30]C.char)(unsafe.Pointer(cstr))
    i := 0
    for ; s[i] != 0; i++ {}
    str := make([]byte, i)
    for j := 0; j < i; j++ {
        str[j] = byte(s[j])
    }
    return string(str)
}
func sliceToC[E any, S ~[]E](s S) (data unsafe.Pointer, length C.size_t, fin func()) {
    if len(s) == 0 {
        return nil, 0, func() {}
    }
    var pin runtime.Pinner
    pin.Pin(&s[0])
    return unsafe.Pointer(&s[0]), C.size_t(len(s)), pin.Unpin
}
func sliceToCZeroTerm[E any, S ~[]E](s S) (data unsafe.Pointer, fin func()) {
    if len(s) == 0 {
        return nil, func() {}
    }
    var zero E
    s = append(slices.Clone(s), zero)
    var pin runtime.Pinner
    pin.Pin(&s[0])
    return unsafe.Pointer(&s[0]), pin.Unpin
}
func stringToC(s string) (_ *C.char, fin func()) {
    var pin runtime.Pinner
    cstr := append([]byte(s), 0)
    pin.Pin(&cstr[0])
    return (*C.char)(unsafe.Pointer(&cstr[0])), pin.Unpin
}
func stringsToC(ss []string) (data **C.char, lengths *C.size_t, fin func()) {
    if len(ss) == 0 {
        return nil, nil, func() {}
    }
    var pin runtime.Pinner
    cstrs := make([][]byte, len(ss))
    for i, s := range ss {
        cstrs[i] = append([]byte(s), 0)
        pin.Pin(&cstrs[i][0])
    }
    pin.Pin(&cstrs[0])
    lens := make([]C.size_t, len(ss))
    for i := range ss {
        lens[i] = C.size_t(len(ss[i]))
    }
    pin.Pin(&lens[0])
    lengths = (*C.size_t)(unsafe.Pointer(&lens[0]))
    ptrs := make([]*C.char, len(ss))
    for i := range ss {
        ptrs[i] = (*C.char)(unsafe.Pointer(&cstrs[i][0]))
    }
    pin.Pin(&ptrs[0])
    data = (**C.char)(unsafe.Pointer(&ptrs[0]))
    fin = pin.Unpin
    return
}
func byteSlicesToC(bs [][]byte) (data **C.uchar, lengths *C.size_t, fin func()) {
    if len(bs) == 0 {
        return nil, nil, func() {}
    }
    var pin runtime.Pinner
    pin.Pin(&bs[0])
    lens := make([]C.size_t, len(bs))
    for i := range bs {
        lens[i] = C.size_t(len(bs[i]))
        if len(bs[i]) > 0 {
            pin.Pin(&bs[i][0])
        }
    }
    pin.Pin(&lens[0])
    lengths = (*C.size_t)(unsafe.Pointer(&lens[0]))
    ptrs := make([]*C.uchar, len(bs))
    for i := range bs {
        ptrs[i] = (*C.uchar)(unsafe.Pointer(&bs[i][0]))
    }
    pin.Pin(&ptrs[0])
    data = (**C.uchar)(unsafe.Pointer(&ptrs[0]))
    fin = pin.Unpin
    return
}
func makeError(ec ErrorCode) error {
    if ec != SUCCESS {
        return &Error{Code: ec}
    } else {
        return nil
    }
}

// Callback handling
var (
    callbackMu sync.Mutex
    callbackUid int = 1
    callbackFns = make(map[int]any)
)
func callbackRegister(fn any) (uid int) {
    if fn == nil { panic("attempt to register nil callback") }
    callbackMu.Lock()
    defer callbackMu.Unlock()
    uid = callbackUid
    callbackFns[uid] = fn
    callbackUid++
    return
}
func callbackUnregister(uid int) {
    callbackMu.Lock()
    defer callbackMu.Unlock()
    delete(callbackFns, uid)
}
func callbackFn(uid int) (fn any) {
    callbackMu.Lock()
    defer callbackMu.Unlock()
    fn = callbackFns[uid]
    return
}

// Error type
type Error struct {
    Code ErrorCode
}

func (err *Error) Error() string {
    return err.Code.String()
}

// ErrorCode enum type
type ErrorCode int
"""

def zipfile_from_url(url: str) -> zipfile.ZipFile:
    with urllib.request.urlopen(url) as r:
        return zipfile.ZipFile(io.BytesIO(r.read()))

def extract_c_source_from_zip_url(
        dstdir: str,
        url: str,
        include_re: str,
        exclude_re: str|None = None,
        preludes: list[tuple[str, str]]|None = None,
        extra_files: list[tuple[str, str]]|None = None,
        replacements: list[tuple[str, str, str]]|None = None,
    ) -> None:
    pathlib.Path(dstdir).mkdir(parents=True, exist_ok=True)
    with zipfile_from_url(url) as ar:
        names = [n for n in ar.namelist() if re.match(include_re, n)]
        if exclude_re is not None:
            names = [n for n in names if not re.match(exclude_re, n)]
        prel = {}
        if preludes is not None:
            for name in names:
                for p in preludes:
                    if re.match(p[0], name):
                        prel[name] = p[1]
                        break
        repl = {}
        if replacements is not None:
            for name in names:
                for r in replacements:
                    if re.match(r[0], name):
                        if name not in repl:
                            repl[name] = []
                        repl[name].append((r[1], r[2]))
        for name in names:
            with ar.open(name) as f:
                out_path = os.path.join(dstdir, os.path.basename(name))
                with open(out_path, "w") as o:
                    text = f.read().decode("utf-8")
                    if name in repl:
                        for r in repl[name]:
                            text = re.sub(r[0], r[1], text, flags=re.MULTILINE)
                    if name in prel:
                        o.write(prel[name])
                    o.write(text)
        if extra_files is not None:
            for extra in extra_files:
                with open(os.path.join(dstdir, extra[0]), "w") as o:
                    o.write(extra[1])

def snake_to_camel(s: str) -> str:
    res = ""
    upper_next = True
    for c in s:
        if c == "_":
            upper_next = True
        else:
            res += c.upper() if upper_next else c
            upper_next = False
    return res

@dataclass
class Struct:
    name: str
    fields: list['Var']
    def __init__(self, ctx: 'Context', name: str, body: str):
        self.name = name

        # Find fields
        if re.search(r"^#", body, re.MULTILINE):
            raise Exception(f"preprocessor directive in body of struct {name}")
        self.fields = []
        for m in re.finditer(r"^ +(?P<type>\w+( +\*|)) +(?P<name>\w+);", body, re.MULTILINE):
            typ = m["type"].replace(" ", "")
            basetyp = typ.replace("*", "")
            self.fields.append(Var(m["name"], Type(basetyp, ctx.typs[basetyp].gobasetyp, ptrlvl=typ.count("*"))))

@dataclass
class Type:
    # type without pointers or return value
    cbasetyp: str
    gobasetyp: str

    goslicelvl: int = 0
    ptrlvl: int = 0
    func_params: list['Var']|None = None
    func_results: list['Var']|None = None

    def go_str(self) -> str:
        if self.cbasetyp == "void" and self.ptrlvl >= 1:
            return "unsafe.Pointer"
        s = ""
        s += "[]"*self.goslicelvl
        s += "*"*self.ptrlvl
        if self.gobasetyp == "func":
            assert self.func_params is not None
            assert self.func_results is not None
            s += "func("
            for i, p in enumerate(self.func_params):
                if i != 0:
                    s += ", "
                s += p.go_str()
            s += ")"
            if len(self.func_results):
                s += " ("
                for i, p in enumerate(self.func_results):
                    if i != 0:
                        s += ", "
                    s += p.go_str()
                s += ")"
        else:
            s += self.gobasetyp
        return s

    def cgo_str(self) -> str:
        s = ""
        s += "[]"*self.goslicelvl
        s += "*"*self.ptrlvl
        if self.gobasetyp == "func":
            s += "*[0]byte"
        else:
            s += "C."+self.cbasetyp
        return s
    
    def conv_to_go(self, expr: str) -> str:
        if self.cbasetyp == "" and self.gobasetyp == "":
            raise Exception("empty type")
        if self.gobasetyp == "":
            raise Exception(f"cannot convert C-only type {self.cgo_str()} to Go")
        if self.cbasetyp == "":
            # Go-only type
            return expr
        if self.cbasetyp == "cl_bool" and self.ptrlvl == 0:
            return f"({expr} != 0)"
        elif self.cbasetyp == "func":
            return f"unsafe.Pointer({expr})"
        else:
            s = self.go_str()
            if self.ptrlvl > 0:
                s = f"({s})"
            return f"{s}({expr})"
    
    def conv_from_go(self, expr: str) -> str:
        if self.cbasetyp == "" and self.gobasetyp == "":
            raise Exception("empty type")
        if self.cbasetyp == "":
            raise Exception(f"cannot convert Go-only type {self.go_str()} to CGo")
        if self.gobasetyp == "":
            # CGo-only type
            return expr
        if self.cbasetyp == "cl_bool" and self.ptrlvl == 0:
            return f"boolToClBool({expr})"
        elif self.cbasetyp == "void" and self.ptrlvl == 1:
            return expr
        elif self.cbasetyp == "void" and self.ptrlvl == 2:
            return f"(*unsafe.Pointer)({expr})"
        elif self.cbasetyp == "func":
            return f"(*[0]byte)(unsafe.Pointer({expr}))"
        else:
            s = self.cgo_str()
            if self.ptrlvl >= 1:
                s = f"({s})"
            e = expr
            if self.ptrlvl == 2:
                e = f"unsafe.Pointer({e})"
            return f"{s}({e})"


def make_simple_type(cname: str, goname: str|None = None) -> Type:
        if goname is None:
            goname = snake_to_camel(cname.removeprefix("cl_"))
        return Type(cname, goname)

@dataclass
class Var:
    name: str
    typ: Type

    def __init__(self, name: str, typ: Type):
        assert isinstance(name, str)
        assert isinstance(typ, Type)
        self.name = name
        self.typ = typ

    def go_str(self) -> str:
        return self.name + " " + self.typ.go_str()

    def cgo_str(self) -> str:
        return self.name + " " + self.typ.cgo_str()

@dataclass
class Context:
    typs: dict[str, Type]

    def __init__(self):
        self.typs = {}
    
    def add(self, typ: Type):
        self.typs[typ.cbasetyp] = typ

@dataclass
class Enum:
    ctyp: str
    gotyp: str
    values: list[tuple[str, str]]
    def __init__(self, ctyp: str, body: str, gotyp: str):
        self.ctyp = ctyp
        self.gotyp = gotyp
        def fixval(v):
            if gotyp == "bool":
                return {"0": "false", "CL_FALSE": "false",
                        "1": "true", "CL_TRUE": "true"}[v]
            else:
                return v
        self.values = [(m["name"].removeprefix("CL_"), fixval(m["val"])) for m in
            re.finditer(r"^#define +(?P<name>\w+) +(?P<val>.*)$", body, re.MULTILINE)]

@dataclass
class Function:
    name: str
    typ: Type
    api_version: str
    def __init__(self, ctx: Context, name: str, rettyp: str, params: str, api_version: str):
        self.name = name
        self.api_version = api_version
        def parse_params(params):
            res = []
            for m in re.finditer(r"^ *((const )?(?P<typ_unsigned>unsigned )?(?P<typ_base>\w+)(?P<typ_ptrs>( *\*)*) +(?P<name>\w*)(?P<typ_arr>(\[\w*\])*)|(void \(CL_CALLBACK) *\* *(?P<fn_name>\w+)\)\((?P<fn_params>.[^\)]+)\))(,|$)", params, re.MULTILINE):
                if m["name"] is not None:
                    ptrlvl = m["typ_ptrs"].count("*") if m["typ_ptrs"] is not None else 0
                    arr = ""
                    if m["typ_arr"] is not None:
                        arr = m["typ_arr"]
                        ptrlvl += arr.count("[]")
                        arr = arr.replace("[]", "")
                        if arr != "":
                            raise Exception("only VLA supported (not fixed length)")
                    base = m["typ_base"]
                    if m["typ_unsigned"] is not None:
                        if base != "char":
                            raise Exception("only char supported for unsigned types")
                        base = "u"+base
                    res.append(Var(m["name"], Type(base, ctx.typs[base].gobasetyp, ptrlvl=ptrlvl)))
                elif "fn_name" in m.groupdict():
                    res.append(Var(m["fn_name"], Type("func", "func", func_params=parse_params(m["fn_params"]), func_results=[])))
                else:
                    raise Exception(f"expected plain or callback parameter, got {m}")
            return res
        rbtyp = rettyp.replace(" ", "").replace("*", "")
        rptrlvl = rettyp.count("*")
        results = []
        if not(rbtyp == "void" and rptrlvl == 0):
            results.append(Var("_", Type(rbtyp, ctx.typs[rbtyp].gobasetyp, ptrlvl=rptrlvl)))
        self.typ = Type("func", "func",
            func_params=parse_params(params), func_results=results)

@dataclass
class FunctionStepState:
    code: str
    c_code: str
    cb_code: str
    generic: str # e.g. "E comparable, S ~[]E"
    # List of Go function input parametersd
    in_params: list[Var]
    # List of Go function return parameters
    out_params: list[Var]
    # List of current values in function body
    values: list[Var]
    # List of values to be returned from function
    out_values: list[Var]
    takennames: dict[str,int]
    # Custom data that can be retained between step invocations
    custom_data: dict[str, object]

    def __init__(self, in_params: list[Var]):
        assert isinstance(in_params, list)
        for p in in_params: assert isinstance(p, Var)
        self.code = ""
        self.c_code = ""
        self.cb_code = ""
        self.generic = ""
        self.in_params = in_params.copy()
        self.out_params = []
        self.values = in_params.copy()
        self.out_values = []
        self.takennames = {v.name: 0 for v in self.values}
        self.custom_data = {}

    # Returns the list of in_params variables corresponding to
    # the given names.
    def get_in_params(self, names: list[str]) -> list[Var]:
        p_names = [p.name for p in self.in_params]
        p_idxs = [p_names.index(n) for n in names]
        return [self.in_params[i] for i in p_idxs]

    def get_values(self, names: list[str]) -> list[Var]:
        p_names = [p.name for p in self.values]
        p_idxs = [p_names.index(n) for n in names]
        return [self.values[i] for i in p_idxs]

    # Finds the variables referenced by remove in self.in_params
    # and self.values (must exist).
    #
    # Replaces the self.in_params with fewer new_in_params and
    # replaces all removed self.values with new values.
    #
    # Reassigns names for new values via mkvar. Returns new_in_params
    # and the list of values with actual unique names.
    def replace_in_params(self, remove: list[str], new_in_params: list[Var]) -> tuple[list[Var], list[Var]]:
        p_names = [p.name for p in self.in_params]
        v_names = [p.name for p in self.values]
        p_r_idxs = [p_names.index(n) for n in remove]
        v_r_idxs = [v_names.index(n) for n in remove]
        if len(new_in_params) > len(remove):
            raise Exception("len(new_in_params) must be no more than len(remove)")
        for i in range(len(new_in_params)):
            self.in_params[p_r_idxs[i]] = new_in_params[i]
        p_r_idxs = p_r_idxs[len(new_in_params):]
        p_r_idxs.sort(reverse=True)
        for i in p_r_idxs: self.in_params.pop(i)
        new_values = [Var(name=self.mkvar(self.values[i].name), typ=self.values[i].typ) for i in v_r_idxs]
        for i in range(len(v_r_idxs)): self.values[v_r_idxs[i]] = new_values[i]
        return (new_in_params, new_values)

    def replace_values(self, names: list[str], new_values: list[Var]) -> None:
        if len(names) != len(new_values):
            raise Exception("len(names) must be equal to len(new_values)")
        v_names = [v.name for v in self.values]
        v_idxs = [v_names.index(n) for n in names]
        for i in range(len(v_idxs)):
            self.values[v_idxs[i]] = new_values[i]

    def remove_in_params(self, names: list[str]) -> list[Var]:
        p_names = [v.name for v in self.in_params]
        p_idxs = [p_names.index(n) for n in names]
        ps = [self.in_params[i] for i in p_idxs]
        p_idxs.sort(reverse=True)
        for i in p_idxs: self.in_params.pop(i)
        return ps

    RE_VAR_PREFIX=re.compile(r"^(.*?)(_[0-9]+)?$")
    def mkvar(self, name: str = "v") -> str:
        s = re.sub(self.RE_VAR_PREFIX, r"\1", name)
        if s in self.takennames:
            self.takennames[s] += 1
            s += f"_{self.takennames[s]}"
        self.takennames[s] = 0
        return s

# Single segment of binding code.
class FunctionStep:
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        pass

@dataclass
class FunctionStepConvToC(FunctionStep):
    values_field: Literal["values", "out_values"]
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        new_values = []
        for i, param in enumerate(getattr(s, self.values_field)):
            if param.typ.gobasetyp == "":
                # Already CGo-only type
                new_values.append(param)
                continue
            if param.typ.cbasetyp == "func":
                assert param.typ.func_params is not None
                assert param.typ.func_results is not None
                cb_name = f"go_cl_callback_{func.name}"
                s.c_code += f"extern void {cb_name}("
                for j, p in enumerate(param.typ.func_params):
                    if j != 0:
                        s.c_code += ", "
                    s.c_code += f"{p.typ.cbasetyp}{"*"*p.typ.ptrlvl}"
                s.c_code += ");\n"
                s.cb_code += f"//export {cb_name}\n"
                s.cb_code += f"func {cb_name}("
                for j, p in enumerate(param.typ.func_params):
                    if j != 0:
                        s.cb_code += ", "
                    s.cb_code += p.cgo_str()
                s.cb_code += ") {\n"
                param.typ.func_params = [x for x in param.typ.func_params if x.name != "user_data"]
                step_st = FunctionStepState(param.typ.func_params)
                steps = [FunctionStepConvToGo("values")]
                for step in steps:
                    step(step_st, ctx, func)
                s.cb_code += textwrap.indent(step_st.code, "\t")
                s.cb_code += "\tuid := int(uintptr(unsafe.Pointer(user_data)))\n"
                # TODO: Not every function should be unregistered after a single call.
                # Maybe we can receive whether to unregister through the callback info
                # somehow.
                s.cb_code += "\tdefer callbackUnregister(uid)\n"
                s.cb_code += f"\t(callbackFn(uid).({param.typ.go_str()}))("
                for j, p in enumerate(step_st.values):
                    if j != 0:
                        s.cb_code += ", "
                    s.cb_code += p.name
                s.cb_code += ")\n"
                s.cb_code += "}\n"
                s.code += "var callback_uid unsafe.Pointer\n"
                s.code += "var callback *[0]byte\n"
                s.code += f"if {param.name} != nil {{\n"
                s.code += f"\tcallback_uid = unsafe.Pointer(uintptr(callbackRegister({param.name})))\n"
                s.code += f"\tcallback = (*[0]byte)(C.{cb_name})\n"
                s.code += "}\n"
                new_values.append(Var("callback", param.typ))
            elif param.name == "user_data":
                s.in_params = [x for x in s.in_params if x.name != "user_data"]
                new_values.append(Var("callback_uid", param.typ))
            else:
                name = s.mkvar(param.name)
                s.code += f"{name} := {param.typ.conv_from_go(param.name)}\n"
                new_values.append(Var(name, param.typ))
        setattr(s, self.values_field, new_values)

@dataclass
class FunctionStepConvToGo(FunctionStep):
    values_field: Literal["values", "out_values"]
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        new_values = []
        for i, param in enumerate(getattr(s, self.values_field)):
            if param.typ.cbasetyp == "":
                # Already Go-only type
                new_values.append(param)
                continue
            name = s.mkvar(param.name)
            s.code += f"{name} := {param.typ.conv_to_go(param.name)}\n"
            new_values.append(Var(name, param.typ))
        setattr(s, self.values_field, new_values)

#class FunctionStepGeneric(FunctionStep):
#    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
#        in_names = [p.name for p in s.in_params]
#        if not ("host_ptr" in in_names and "size" in in_names):
#            return
#        s.generic += "E comparable, S ~[]E"

@dataclass
class SliceHint:
    data_ptr: str
    data_len: str|None = None # Assuming zero-terminated if None
    actual_len: str|None = None # Slice is returned if not None
    data_count: str|None = None
    kind: Literal["array", "bytes", "string", "bytesarr", "stringarr"] = "array"

SLICE_HINTS = {
    r"clGetPlatformIDs": [SliceHint("platforms", "num_entries", "num_platforms")],
    r"clGetDeviceIDs": [SliceHint("devices", "num_entries", "num_devices")],
    r"clCreateSubDevice": [SliceHint("out_devices", "num_devices", "num_devices_ret"), SliceHint("properties")],
    r"clCreateContext": [SliceHint("devices", "num_devices"), SliceHint("properties")],
    r"clCreateContextFromType": [SliceHint("properties")],
    r"clGetSupportedImageFormats": [SliceHint("image_formats", "num_entries", "num_image_formats")],
    r"clCreateProgramWithSource": [SliceHint("strings", "lengths", data_count="count", kind="stringarr")],
    r"clCreateProgramWithBinary": [SliceHint("device_list", "num_devices"), SliceHint("binaries", "lengths", kind="bytesarr")],
    r"clCreateProgramWithBuiltInKernels": [SliceHint("device_list", "num_devices"), SliceHint("kernel_names", kind="string")],
    r"clBuildProgram": [SliceHint("device_list", "num_devices")],
    r"clCompileProgram": [SliceHint("device_list", "num_devices"), SliceHint("options", kind="string")],
    r"clLinkProgram": [SliceHint("device_list", "num_devices"), SliceHint("input_programs", "num_input_programs"), SliceHint("options", kind="string")],
    r"clCreateKernel": [SliceHint("kernel_name", kind="string")],
    r"clCreateKernelsInProgram": [SliceHint("kernels", "num_kernels", "num_kernels_ret")],
    r"clWaitForEvents": [SliceHint("event_list", "num_events")],
    r"clEnqueue(?!(WaitForEvents|Marker|Barrier)$)\w+": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    r"clEnqueueWaitForEvents": [SliceHint("event_list", "num_events")],
    r"clGetExtensionFunctionAddressForPlatform": [SliceHint("func_name", kind="string")],
    r"clGetExtensionFunctionAddress": [SliceHint("func_name", kind="string")],
}

@dataclass
class FunctionStepSlice(FunctionStep):
    kind: Literal["pre_conv", "post_conv"]
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        hints = [h for [pat, hs] in SLICE_HINTS.items() for h in hs if re.fullmatch(pat, func.name)]
        for hint in hints:
            if hint.kind == "array":
                # Slice is output parameter
                if hint.actual_len is not None:
                    assert hint.data_len is not None
                    if self.kind == "pre_conv":
                        [vdata, vlen, vactlen] = s.get_values([hint.data_ptr, hint.data_len, hint.actual_len])
                        s.custom_data["array_res_slicetyp"] = Type("", vdata.typ.gobasetyp, goslicelvl=1)
                        # Prevent conversion of values
                        s.replace_values([hint.data_ptr, hint.data_len, hint.actual_len], [
                                Var(vdata.name, Type(vdata.typ.cbasetyp, "", ptrlvl=1)),
                                Var(vlen.name, Type(vlen.typ.cbasetyp, "")),
                                Var(vactlen.name, Type(vactlen.typ.cbasetyp, "", ptrlvl=1)),
                            ])
                    else:
                        tslc = s.custom_data["array_res_slicetyp"]
                        assert isinstance(tslc, Type)
                        [vdata, vlen, vactlen] = s.get_values([hint.data_ptr, hint.data_len, hint.actual_len])

                        # Call function with null params to find out actual len first
                        nactlen = s.mkvar(f"{hint.data_ptr}_actual_len")
                        s.code += f"var {nactlen} {Type(vactlen.typ.cbasetyp, "").cgo_str()}\n"
                        s.code += f"C.{func.name}("
                        for i, v in enumerate(s.values):
                            if i != 0:
                                s.code += ", "
                            if v.name == hint.data_ptr:
                                s.code += "nil"
                            elif v.name == hint.data_len:
                                s.code += f"0"
                            elif v.name == hint.actual_len:
                                s.code += f"&{nactlen}"
                            else:
                                s.code += v.name
                        s.code += ")\n"

                        s.remove_in_params([hint.data_ptr, hint.data_len, hint.actual_len])

                        vslc = Var(s.mkvar(vdata.name), tslc)
                        s.code += f"{vslc.name} := make({vslc.typ.go_str()}, {nactlen})\n"
                        nfin = s.mkvar(f"{vdata.name}_fin")
                        s.code += f"{vdata.name}, {vlen.name}, {nfin} := sliceToC({vslc.name})\n"
                        s.code += f"defer {nfin}()\n"

                        # Convert manually
                        vdata.name = f"(*C.{vdata.typ.cbasetyp})({vdata.name})"
                        vlen.name = f"C.{vlen.typ.cbasetyp}({vlen.name})"

                        # No need to query actual length anymore
                        vactlen.name = "nil"

                        s.out_values.append(vslc)
                        s.out_params.append(Var(f"_{hint.data_ptr}", vslc.typ))
                elif hint.data_len is None:
                    # Slice is zero sentinel terminated input parameter
                    if self.kind != "pre_conv": continue

                    [vdata] = s.get_in_params([hint.data_ptr])
                    ([vslc], [vdata]) = s.replace_in_params(
                        [hint.data_ptr],
                        [Var(vdata.name, Type("", vdata.typ.gobasetyp, goslicelvl=1))])
                    nfin = s.mkvar(f"{vdata.name}_fin")
                    s.code += f"{vdata.name}, {nfin} := sliceToCZeroTerm({vslc.name})\n"
                    s.code += f"defer {nfin}()\n"
                else:
                    # Slice is input parameter with specified size
                    if self.kind != "pre_conv": continue

                    [vdata, vlen] = s.get_in_params([hint.data_ptr, hint.data_len])
                    ([vslc], [vdata, vlen]) = s.replace_in_params(
                        [hint.data_ptr, hint.data_len],
                        [Var(vdata.name, Type("", vdata.typ.gobasetyp, goslicelvl=1))])
                    nfin = s.mkvar(f"{vdata.name}_fin")
                    s.code += f"{vdata.name}, {vlen.name}, {nfin} := sliceToC({vslc.name})\n"
                    s.code += f"defer {nfin}()\n"
            elif hint.kind == "string":
                # Zero-terminated input string
                if self.kind != "pre_conv": continue

                [vdata] = s.get_in_params([hint.data_ptr])
                ([vstr], [vdata]) = s.replace_in_params(
                    [hint.data_ptr],
                    [Var(vdata.name, Type("", "string"))])
                nfin = s.mkvar(f"{vdata.name}_fin")
                s.code += f"{vdata.name}, {nfin} := stringToC({vstr.name})\n"
                vdata.typ = Type("char", "", ptrlvl=1)
                s.code += f"defer {nfin}()\n"
            elif hint.kind == "stringarr":
                # Array of input strings with size specifications
                if self.kind != "pre_conv": continue

                assert hint.data_len is not None
                assert hint.data_count is not None
                [vdata, vlens, vcnt] = s.get_in_params([hint.data_ptr, hint.data_len, hint.data_count])
                ([vstrs], [vdata, vlens, vcnt]) = s.replace_in_params(
                    [hint.data_ptr, hint.data_len, hint.data_count],
                    [Var(vdata.name, Type("", "string", goslicelvl=1))])
                nfin = s.mkvar(f"{vdata.name}_fin")
                s.code += f"{vdata.name}, {vlens.name}, {nfin} := stringsToC({vstrs.name})\n"
                vdata.typ = Type("char", "", ptrlvl=2)
                vlens.typ = Type("size_t", "", ptrlvl=1)
                s.code += f"{vcnt.name} := len({vstrs.name})\n"
                s.code += f"defer {nfin}()\n"
            elif hint.kind == "bytesarr":
                # Array of input byte arrays with size specifications
                if self.kind != "pre_conv": continue

                assert hint.data_len is not None
                assert hint.data_count is None
                [vdata, vlens] = s.get_in_params([hint.data_ptr, hint.data_len])
                ([vslcs], [vdata, vlens]) = s.replace_in_params(
                    [hint.data_ptr, hint.data_len],
                    [Var(vdata.name, Type("", "byte", goslicelvl=2))])
                nfin = s.mkvar(f"{vdata.name}_fin")
                s.code += f"{vdata.name}, {vlens.name}, {nfin} := byteSlicesToC({vslcs.name})\n"
                vdata.typ = Type("uchar", "", ptrlvl=2)
                vlens.typ = Type("size_t", "", ptrlvl=1)
                s.code += f"defer {nfin}()\n"


class FunctionStepCall(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        assert func.typ.func_params is not None
        assert func.typ.func_results is not None
        params = func.typ.func_params
        results = func.typ.func_results
        returns_err = (not "errcode_ret" in [p.name for p in params] and
            len(results) == 1 and results[0].typ.cbasetyp == "cl_int")
        if func.name == "clGetExtensionFunctionAddressForPlatform":
            print(results)

        if len(results) > 0:
            assert len(results) == 1
            retname = s.mkvar("res")
            s.code += f"{retname} := "
        s.code += f"C.{func.name}("
        for i, v in enumerate(s.values):
            if i != 0:
                s.code += ", "
            s.code += v.name
        s.code += ")\n"
        s.values = []
        if len(results) > 0:
            if returns_err:
                s.out_params.append(Var("_err", Type("", "error")))
                s.out_values.append(Var(f"makeError(ErrorCode({retname}))", Type("", "error")))
            else:
                s.out_params.insert(0, Var("_res", results[0].typ))
                s.out_values.insert(0, Var(retname, s.out_params[0].typ))

@dataclass
class ResultHint:
    param: str
    kind: Literal["normal", "error"] = "normal"

RESULT_HINTS: dict[str, list[ResultHint]] = {
    r"\w+": [ResultHint("errcode_ret", kind="error")],
    r"clGetDeviceAndHostTimer": [ResultHint("device_timestamp"), ResultHint("host_timestamp")],
    r"clGetHostTimer": [ResultHint("host_timestamp")],
}

# Turns function results passed as pointers in the C API into
# results in the Go API.
#
# Parameters returned as slices are handled in FunctionStepSlice.
class FunctionStepParamResults(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        hints = [h for [pat, hs] in RESULT_HINTS.items() for h in hs if re.fullmatch(pat, func.name)]
        for hint in hints:
            in_names = [p.name for p in s.in_params]
            v_names = [p.name for p in s.values]
            if hint.param not in in_names:
                continue
            ip = in_names.index(hint.param)
            iv = v_names.index(hint.param)
            vres = s.mkvar(f"{hint.param}")
            btyp = s.in_params[ip].typ.cbasetyp
            s.code += f"var {vres} {Type(btyp, "").cgo_str()}\n"
            s.values[iv] = Var(f"&{vres}", Type(btyp, "", ptrlvl=1))
            if hint.kind == "error":
                otyp = Type("", "error")
                s.out_values.append(Var(f"makeError(ErrorCode({vres}))", otyp))
                s.out_params.append(Var(f"_{hint.param}", otyp))
            else:
                otyp = ctx.typs[btyp]
                s.out_values.append(Var(f"{vres}", otyp))
                s.out_params.append(Var(f"_{hint.param}", otyp))
            s.in_params.pop(ip)

class FunctionStepRet(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        if len(s.out_values) == 0:
            return
        s.code += "return "
        for i, param in enumerate(s.out_values):
            if i != 0:
                s.code += ", "
            s.code += param.name
        s.code += "\n"
        s.out_values = []

def generate_bindings(dstfile: str, go_prelude: str, headers: list[str]) -> None:
    with open(dstfile, "w") as o, open(dstfile+".h", "w") as o_c:
        ctx = Context()

        ctx.add(make_simple_type("char", "int8"))
        ctx.add(make_simple_type("uchar", "uint8"))
        ctx.add(make_simple_type("size_t", "uint64"))
        ctx.add(make_simple_type("cl_bool", "bool"))
        ctx.add(make_simple_type("cl_char", "int8"))
        ctx.add(make_simple_type("cl_uchar", "uint8"))
        ctx.add(make_simple_type("cl_short", "int16"))
        ctx.add(make_simple_type("cl_ushort", "uint16"))
        ctx.add(make_simple_type("cl_int", "int32"))
        ctx.add(make_simple_type("cl_uint", "uint32"))
        ctx.add(make_simple_type("cl_long", "int64"))
        ctx.add(make_simple_type("cl_ulong", "uint64"))
        ctx.add(make_simple_type("cl_half", "float16.Float16"))
        ctx.add(make_simple_type("cl_float", "float32"))
        ctx.add(make_simple_type("cl_double", "float64"))
        ctx.add(make_simple_type("void", "void"))

        def docs_url(typ: str) -> str:
            return f"https://registry.khronos.org/OpenCL/specs/unified/refpages/man/html/{typ}.html"

        o.write(go_prelude)
        for header in headers:
            o.write(f"// BEGIN {dstfile} //\n\n")
            hdr = ""
            with open(header) as f:
                hdr = f.read()

            o.write("// Typedefs\n\n")
            typedefs = [m["name"] for m in
                re.finditer(r"^typedef [^\n{}]+ (?P<name>cl_[a-z0-9_]+);", hdr, re.MULTILINE)]
            for name in typedefs:
                if name in ctx.typs:
                    continue
                ctx.add(make_simple_type(name))
                o.write(f"// See {docs_url(name)}\n")
                o.write(f"type {ctx.typs[name].go_str()} {ctx.typs[name].cgo_str()}\n")
            o.write("\n")

            o.write("// Structs\n\n")
            structs = [Struct(ctx, m["name"], m["body"]) for m in
                re.finditer(r"^typedef struct[^{\n]*\{(?P<body>(\n[ #][^\n]+)+\n)\} *(?P<name>cl_\w+);", hdr, re.MULTILINE)]
            for struct in structs:
                name = struct.name
                ctx.add(make_simple_type(name))
                o.write(f"// See {docs_url(name)}\n")
                o.write(f"type {ctx.typs[name].go_str()} {ctx.typs[name].cgo_str()}\n")
                for field in struct.fields:
                    fname = snake_to_camel(field.name)
                    o.write(f"func (s *{ctx.typs[name].go_str()}) {fname}() {field.typ.go_str()} {{")
                    o.write(f" return {field.typ.conv_to_go(f"s.{field.name}")} ")
                    o.write(f"}}\n")
                    o.write(f"func (s *{ctx.typs[name].go_str()}) Set{fname}(v {field.typ.go_str()}) {{")
                    o.write(f" s.{field.name} = {field.typ.conv_from_go("v")} ")
                    o.write(f"}}\n")
            o.write("\n")

            if os.path.basename(header) == "cl.h":
                o.write("// Enums\n\n")
                enums = []
                err_codes = re.search(r"^\/\* Error Codes \*\/\n(?P<body>(.+\n\n?)+)", hdr, re.MULTILINE)
                assert err_codes is not None
                enums.append(Enum(
                        "int",
                        err_codes["body"],
                        gotyp="ErrorCode",
                    ))
                for m in re.finditer(r"^\/\* (?P<type>cl_\w+)( and (?P<type2>cl_\w+))?( - bitfield)? \*\/\n(?P<body>([^\n].*\n)+)", hdr, re.MULTILINE):
                    ctyp = m["type"]
                    gotyp = ""
                    if ctyp in ctx.typs:
                        gotyp = ctx.typs[ctyp].go_str()
                    else:
                        gotyp = snake_to_camel(ctyp.removeprefix("cl_"))
                    enums.append(Enum(ctyp, m["body"], gotyp))
                for enum in enums:
                    o.write(f"// See {docs_url("enums")}\n")
                    o.write(f"const ( // {enum.gotyp}\n")
                    for value in enum.values:
                        o.write(f"\t{value[0]} {enum.gotyp} = {value[1]}\n")
                    o.write(f")\n")

                for enum in enums:
                    if enum.ctyp in ("cl_version", "cl_bool"):
                        continue
                    o.write(f"func (v {enum.gotyp}) String() string {{\n")
                    o.write("\tswitch v {\n")
                    for value in enum.values:
                        if "/* deprecated */" in value[1]:
                            # Some enum values have been renamed with the
                            # old name marked as deprecated; we want to avoid
                            # duplicates
                            continue
                        o.write(f"\tcase {value[0]}: return \"{value[0]}\"\n")
                    o.write(f"\tdefault: return fmt.Sprintf(\"UNKNOWN (%d)\", v)\n")
                    o.write(f"\t}}\n")
                    o.write(f"}}\n")
                o.write("\n")

                o.write("// Functions\n\n")
                funcs = [Function(ctx, m["name"], m["type"], m["params"], m["api_version"]) for m in
                    re.finditer(r"^extern CL_API_ENTRY (CL_API_PREFIX__\w+ )?(?P<type>[\w \*]+) CL_API_CALL\n(?P<name>cl\w+)\((?P<params>(.+,\n)*.+)\) CL_API_SUFFIX__(?P<api_version>\w+);", hdr, re.MULTILINE)]
                for func in funcs:
                    if func.name == "clEnqueueNativeKernel":
                        # TODO This function handles callbacks a bit strangely
                        continue
                        #func.typ.func_params[2].name = "user_data"
                        #func.typ.func_params[1].typ.func_params = [Var("user_data", Type("void", "void", ptrlvl=1))]

                    steps = [
                        FunctionStepSlice("pre_conv"),
                        FunctionStepParamResults(),
                        FunctionStepConvToC("values"),
                        FunctionStepSlice("post_conv"),
                        FunctionStepCall(),
                        FunctionStepConvToGo("out_values"),
                        FunctionStepRet(),
                    ]
                    assert func.typ.func_params is not None
                    assert func.typ.func_results is not None
                    step_st = FunctionStepState(func.typ.func_params)
                    for step in steps:
                        step(step_st, ctx, func)

                    o_c.write(step_st.c_code)
                    o.write(step_st.cb_code)

                    goname = func.name.removeprefix("cl")
                    o.write(f"// See {docs_url(func.name)}\n")
                    o.write(f"func {goname}")
                    if step_st.generic != "":
                        o.write(f"[{step_st.generic}]")
                    o.write("(")
                    for i, param in enumerate(step_st.in_params):
                        if i != 0:
                            o.write(", ")
                        o.write(param.go_str())
                    o.write(") ")
                    if len(step_st.out_params):
                        o.write("(")
                        for i, param in enumerate(step_st.out_params):
                            if i != 0:
                                o.write(", ")
                            o.write(param.go_str())
                        o.write(") ")
                    o.write("{\n")
                    o.write(textwrap.indent(step_st.code, "\t"))
                    o.write("}\n")
                o.write("\n")

            o.write(f"// END {dstfile} //\n\n")

if __name__ == "__main__":
    if not os.path.isdir("cl-3.1"):
        extract_c_source_from_zip_url(
            "cl-3.1",
            OPENCL_ICD_LOADER_ZIP_URL,
            OPENCL_ICD_LOADER_INCLUDE_RE,
            exclude_re = OPENCL_ICD_LOADER_EXCLUDE_RE,
            preludes = OPENCL_ICD_LOADER_PRELUDES,
            extra_files = OPENCL_ICD_LOADER_EXTRA_FILES,
        )
        extract_c_source_from_zip_url(
            "cl-3.1/inc/CL",
            OPENCL_HEADERS_ZIP_URL,
            OPENCL_HEADERS_INCLUDE_RE,
            replacements = OPENCL_HEADERS_REPLACEMENTS,
        )
    generate_bindings(
        "cl-3.1/cl.go",
        GO_PRELUDE,
        [
            "cl-3.1/inc/CL/cl_platform.h",
            "cl-3.1/inc/CL/cl.h",
        ],
    )