import io
import os
import pathlib
import re
import urllib.request
import zipfile
import os.path
import textwrap
from dataclasses import dataclass

OPENCL_ICD_LOADER_ZIP_URL = "https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/refs/tags/v2026.05.29.zip"
OPENCL_HEADERS_ZIP_URL = "https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/tags/v2026.05.29.zip"

OPENCL_ICD_LOADER_INCLUDE_RE = r"^OpenCL-ICD-Loader-[^/]+/(loader|include)/.+\.[ch]$"
OPENCL_ICD_LOADER_EXCLUDE_RE = r".+/cllayerinfo\.c$"
OPENCL_ICD_LOADER_PRELUDES = [
    (r".+/loader/windows/.+\.[ch]$", "//go:build windows\n\n"),
    (r".+/loader/linux/.+\.[ch]$", "//go:build linux\n\n"),
]
OPENCL_ICD_LOADER_EXTRA_FILES = [
    ("icd_cmake_config.h", "#define HAVE_SECURE_GETENV\n#define HAVE___SECURE_GETENV"),
]

OPENCL_HEADERS_INCLUDE_RE = r"^OpenCL-Headers-[^/]+/CL/.+\.[h]$"
OPENCL_HEADERS_REPLACEMENTS = [
    (r"^.+/cl.h$", r"^#if defined\(CL_VERSION_2_0\) && __CL_HAS_ANON_UNION__\n([^#]*\n)+#endif\n", ""),
]

GO_PRELUDE = """// Code generated by generate.py; DO NOT EDIT.
package cl

/*
#cgo CFLAGS: -DCL_TARGET_OPENCL_VERSION=310
#cgo CFLAGS: -DCL_NO_NON_ICD_DISPATCH_EXTENSION_PROTOTYPES
#cgo CFLAGS: -DCL_ENABLE_LAYERS
#cgo CFLAGS: -Wno-deprecated-declarations
#cgo CFLAGS: -Iinc/
#cgo windows LDFLAGS: -lcfgmgr32 -lruntimeobject -lOle32
#include "inc/CL/cl.h"
#include "cl.go.h"
*/
import "C"

import (
    "fmt"
    "runtime"
    "slices"
    "sync"
    "unsafe"
)

// Custom utilities
func boolToClBool(b bool) C.cl_bool {
    if b {
        return 1
    } else {
        return 0
    }
}
func cstringToString(cstr *C.char) string {
	s := (*[1<<30]C.char)(unsafe.Pointer(cstr))
    i := 0
    for ; s[i] != 0; i++ {}
    str := make([]byte, i)
	for j := 0; j < i; j++ {
		str[j] = byte(s[j])
	}
    return string(str)
}
func stringToC(s string) (_ *C.char, fin func()) {
    var pin runtime.Pinner
    cstr := append([]byte(s), 0)
    pin.Pin(&cstr[0])
    return (*C.char)(unsafe.Pointer(&cstr[0])), pin.Unpin
}
func stringsToC(ss []string) (data **C.char, lengths *C.size_t, fin func()) {
    if len(ss) == 0 {
        return nil, nil, func() {}
    }
    var pin runtime.Pinner
    cstrs := make([][]byte, len(ss))
    for i, s := range ss {
        cstrs[i] = append([]byte(s), 0)
        pin.Pin(&cstrs[i][0])
    }
    pin.Pin(&cstrs[0])
    lens := make([]C.size_t, len(ss))
    for i := range ss {
        lens[i] = C.size_t(len(ss[i]))
    }
    pin.Pin(&lens[0])
    lengths = (*C.size_t)(unsafe.Pointer(&lens[0]))
    ptrs := make([]*C.char, len(ss))
    for i := range ss {
        ptrs[i] = (*C.char)(unsafe.Pointer(&cstrs[i][0]))
    }
    pin.Pin(&ptrs[0])
    data = (**C.char)(unsafe.Pointer(&ptrs[0]))
    fin = pin.Unpin
    return
}
func byteArraysToC(bs [][]byte) (data **C.uchar, lengths *C.size_t, fin func()) {
    if len(bs) == 0 {
        return nil, nil, func() {}
    }
    var pin runtime.Pinner
    pin.Pin(&bs[0])
    lens := make([]C.size_t, len(bs))
    for i := range bs {
        lens[i] = C.size_t(len(bs[i]))
        if len(bs[i]) > 0 {
            pin.Pin(&bs[i][0])
        }
    }
    pin.Pin(&lens[0])
    lengths = (*C.size_t)(unsafe.Pointer(&lens[0]))
    ptrs := make([]*C.uchar, len(bs))
    for i := range bs {
        ptrs[i] = (*C.uchar)(unsafe.Pointer(&bs[i][0]))
    }
    pin.Pin(&ptrs[0])
    data = (**C.uchar)(unsafe.Pointer(&ptrs[0]))
    fin = pin.Unpin
    return
}
func makeError(ec ErrorCode) error {
    if ec != SUCCESS {
        return &Error{Code: ec}
    } else {
        return nil
    }
}

// Callback handling
var (
    callbackMu sync.Mutex
    callbackUid int = 1
    callbackFns = make(map[int]any)
)
func callbackRegister(fn any) (uid int) {
    if fn == nil { panic("attempt to register nil callback") }
    callbackMu.Lock()
    defer callbackMu.Unlock()
    uid = callbackUid
    callbackFns[uid] = fn
    callbackUid++
    return
}
func callbackUnregister(uid int) {
    callbackMu.Lock()
    defer callbackMu.Unlock()
    delete(callbackFns, uid)
}
func callbackFn(uid int) (fn any) {
    callbackMu.Lock()
    defer callbackMu.Unlock()
    fn = callbackFns[uid]
    return
}

// Error type
type Error struct {
    Code ErrorCode
}

func (err *Error) Error() string {
    return err.Code.String()
}

// ErrorCode enum type
type ErrorCode int
"""

def zipfile_from_url(url: str) -> zipfile.ZipFile:
    with urllib.request.urlopen(url) as r:
        return zipfile.ZipFile(io.BytesIO(r.read()))

def extract_c_source_from_zip_url(
        dstdir: str,
        url: str,
        include_re: str,
        exclude_re: str|None = None,
        preludes: list[tuple[str, str]] = None,
        extra_files: list[tuple[str, str]]|None = None,
        replacements: list[tuple[str, str]]|None = None,
    ) -> None:
    pathlib.Path(dstdir).mkdir(parents=True, exist_ok=True)
    with zipfile_from_url(url) as ar:
        names = [n for n in ar.namelist() if re.match(include_re, n)]
        if exclude_re is not None:
            names = [n for n in names if not re.match(exclude_re, n)]
        prel = {}
        if preludes is not None:
            for name in names:
                for p in preludes:
                    if re.match(p[0], name):
                        prel[name] = p[1]
                        break
        repl = {}
        if replacements is not None:
            for name in names:
                for r in replacements:
                    if re.match(r[0], name):
                        if name not in repl:
                            repl[name] = []
                        repl[name].append((r[1], r[2]))
        for name in names:
            with ar.open(name) as f:
                out_path = os.path.join(dstdir, os.path.basename(name))
                with open(out_path, "w") as o:
                    text = f.read().decode("utf-8")
                    if name in repl:
                        for r in repl[name]:
                            text = re.sub(r[0], r[1], text, flags=re.MULTILINE)
                    if name in prel:
                        o.write(prel[name])
                    o.write(text)
        if extra_files is not None:
            for extra in extra_files:
                with open(os.path.join(dstdir, extra[0]), "w") as o:
                    o.write(extra[1])

def snake_to_camel(s: str) -> str:
    res = ""
    upper_next = True
    for c in s:
        if c == "_":
            upper_next = True
        else:
            res += c.upper() if upper_next else c
            upper_next = False
    return res

@dataclass
class Struct:
    name: str
    fields: list['Var']
    def __init__(self, ctx: 'Context', name: str, body: str):
        self.name = name

        # Find fields
        if re.search(r"^#", body, re.MULTILINE):
            raise Exception(f"preprocessor directive in body of struct {name}")
        self.fields = []
        for m in re.finditer(r"^ +(?P<type>\w+( +\*|)) +(?P<name>\w+);", body, re.MULTILINE):
            typ = m["type"].replace(" ", "")
            basetyp = typ.replace("*", "")
            self.fields.append(Var(m["name"], Type(basetyp, ctx.typs[basetyp].gobasetyp, ptrlvl=typ.count("*"))))

@dataclass
class Type:
    # type without pointers or return value
    cbasetyp: str
    gobasetyp: str

    goslice: bool = False
    ptrlvl: int = 0
    func_params: list['Var']|None = None
    func_results: list['Var']|None = None

    def go_str(self) -> str:
        if self.cbasetyp == "void" and self.ptrlvl >= 1:
            return "unsafe.Pointer"
        s = "*"*self.ptrlvl
        if self.goslice:
            s += "[]"
        if self.gobasetyp == "func":
            s += "func("
            for i, p in enumerate(self.func_params):
                if i != 0:
                    s += ", "
                s += p.go_str()
            s += ")"
            if len(self.func_results):
                s += " ("
                for i, p in enumerate(self.func_results):
                    if i != 0:
                        s += ", "
                    s += p.go_str()
                s += ")"
        else:
            s += self.gobasetyp
        return s

    def cgo_str(self) -> str:
        s = "*"*self.ptrlvl
        if self.goslice:
            s += "[]"
        if self.gobasetyp == "func":
            s += "*[0]byte"
        else:
            s += "C."+self.cbasetyp
        return s
    
    def conv_to_go(self, expr: str) -> str:
        if self.cbasetyp == "" and self.gobasetyp == "":
            raise Exception("empty type")
        if self.gobasetyp == "":
            raise Exception(f"cannot convert C-only type {self.cgo_str()} to Go")
        if self.cbasetyp == "":
            # Go-only type
            return expr
        if self.cbasetyp == "cl_bool" and self.ptrlvl == 0:
            return f"({expr} != 0)"
        elif self.cbasetyp == "func":
            return f"unsafe.Pointer({expr})"
        else:
            s = self.go_str()
            if self.ptrlvl > 0:
                s = f"({s})"
            return f"{s}({expr})"
    
    def conv_from_go(self, expr: str) -> str:
        if self.cbasetyp == "" and self.gobasetyp == "":
            raise Exception("empty type")
        if self.cbasetyp == "":
            raise Exception(f"cannot convert Go-only type {self.go_str()} to CGo")
        if self.gobasetyp == "":
            # CGo-only type
            return expr
        if self.cbasetyp == "cl_bool" and self.ptrlvl == 0:
            return f"boolToClBool({expr})"
        elif self.cbasetyp == "void" and self.ptrlvl == 1:
            return expr
        elif self.cbasetyp == "void" and self.ptrlvl == 2:
            return f"(*unsafe.Pointer)({expr})"
        elif self.cbasetyp == "func":
            return f"(*[0]byte)(unsafe.Pointer({expr}))"
        else:
            s = self.cgo_str()
            if self.ptrlvl >= 1:
                s = f"({s})"
            e = expr
            if self.ptrlvl == 2:
                e = f"unsafe.Pointer({e})"
            return f"{s}({e})"


def make_simple_type(cname: str, goname: str|None = None) -> Type:
        if goname is None:
            goname = snake_to_camel(cname.removeprefix("cl_"))
        return Type(cname, goname)

@dataclass
class Var:
    name: str
    typ: Type

    def __init__(self, name: str, typ: Type):
        assert isinstance(name, str)
        assert isinstance(typ, Type)
        self.name = name
        self.typ = typ

    def go_str(self) -> str:
        return self.name + " " + self.typ.go_str()

    def cgo_str(self) -> str:
        return self.name + " " + self.typ.cgo_str()

@dataclass
class Context:
    typs: dict[str, Type]

    def __init__(self):
        self.typs = {}
    
    def add(self, typ: Type):
        self.typs[typ.cbasetyp] = typ

@dataclass
class Enum:
    ctyp: str
    gotyp: str
    values: list[tuple[str, str]]
    def __init__(self, ctyp: str, body: str, gotyp: str):
        self.ctyp = ctyp
        self.gotyp = gotyp
        def fixval(v):
            if gotyp == "bool":
                return {"0": "false", "CL_FALSE": "false",
                        "1": "true", "CL_TRUE": "true"}[v]
            else:
                return v
        self.values = [(m["name"].removeprefix("CL_"), fixval(m["val"])) for m in
            re.finditer(r"^#define +(?P<name>\w+) +(?P<val>.*)$", body, re.MULTILINE)]

@dataclass
class Function:
    name: str
    typ: Type
    api_version: str
    def __init__(self, ctx: Context, name: str, rettyp: str, params: str, api_version: str):
        self.name = name
        self.api_version = api_version
        def parse_params(params):
            res = []
            for m in re.finditer(r"^ *((const )?(?P<typ_unsigned>unsigned )?(?P<typ_base>\w+)(?P<typ_ptrs>( *\*)*) +(?P<name>\w*)(?P<typ_arr>(\[\w*\])*)|(void \(CL_CALLBACK) *\* *(?P<fn_name>\w+)\)\((?P<fn_params>.[^\)]+)\))(,|$)", params, re.MULTILINE):
                if m["name"] is not None:
                    ptrlvl = m["typ_ptrs"].count("*") if m["typ_ptrs"] is not None else 0
                    arr = ""
                    if m["typ_arr"] is not None:
                        arr = m["typ_arr"]
                        ptrlvl += arr.count("[]")
                        arr = arr.replace("[]", "")
                        if arr != "":
                            raise Exception("only VLA supported (not fixed length)")
                    base = m["typ_base"]
                    if m["typ_unsigned"] is not None:
                        if base != "char":
                            raise Exception("only char supported for unsigned types")
                        base = "u"+base
                    res.append(Var(m["name"], Type(base, ctx.typs[base].gobasetyp, ptrlvl=ptrlvl)))
                elif "fn_name" in m.groupdict():
                    res.append(Var(m["fn_name"], Type("func", "func", func_params=parse_params(m["fn_params"]), func_results=[])))
                else:
                    raise Exception(f"expected plain or callback parameter, got {m}")
            return res
        rtyp = rettyp.replace(" ", "").replace("*", "")
        results = []
        if rtyp != "void":
            results.append(Var("_", Type(rtyp, ctx.typs[rtyp].gobasetyp, ptrlvl=rettyp.count("*"))))
        self.typ = Type("func", "func",
            func_params=parse_params(params), func_results=results)

@dataclass
class FunctionStepState:
    code: str
    c_code: str
    cb_code: str
    generic: str # e.g. "E comparable, S ~[]E"
    in_params: list[Var]
    out_params: list[Var]
    values: list[Var]
    takennames: dict[str,int]

    def __init__(self, in_params: list[Var], out_params: list[Var]):
        assert isinstance(in_params, list)
        assert isinstance(out_params, list)
        for p in in_params: assert isinstance(p, Var)
        for p in out_params: assert isinstance(p, Var)
        self.code = ""
        self.c_code = ""
        self.cb_code = ""
        self.generic = ""
        self.in_params = in_params.copy()
        self.out_params = out_params.copy()
        self.values = in_params.copy()
        self.takennames = {v.name: 0 for v in self.values}

    def mkvar(self, pfx: str = "v") -> str:
        if self.takennames is None:
            self.takennames = {}
        s = pfx
        if s in self.takennames:
            self.takennames[s] += 1
            s += f"_{self.takennames[s]}"
        else:
            self.takennames[s] = 0
        return s

# Single segment of binding code.
class FunctionStep:
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        pass

class FunctionStepConvToC(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        new_values = []
        for i, param in enumerate(s.values):
            if param.typ.gobasetyp == "":
                # Already CGo-only type
                new_values.append(param)
                continue
            if param.typ.cbasetyp == "func":
                cb_name = f"go_cl_callback_{func.name}"
                s.c_code += f"extern void {cb_name}("
                for j, p in enumerate(param.typ.func_params):
                    if j != 0:
                        s.c_code += ", "
                    s.c_code += f"{p.typ.cbasetyp}{"*"*p.typ.ptrlvl}"
                s.c_code += ");\n"
                s.cb_code += f"//export {cb_name}\n"
                s.cb_code += f"func {cb_name}("
                for j, p in enumerate(param.typ.func_params):
                    if j != 0:
                        s.cb_code += ", "
                    s.cb_code += p.cgo_str()
                s.cb_code += ") {\n"
                param.typ.func_params = [x for x in param.typ.func_params if x.name != "user_data"]
                step_st = FunctionStepState(param.typ.func_params, param.typ.func_results)
                steps = [FunctionStepConvToGo()]
                for step in steps:
                    step(step_st, ctx, func)
                s.cb_code += textwrap.indent(step_st.code, "\t")
                s.cb_code += "\tuid := int(uintptr(unsafe.Pointer(user_data)))\n"
                # TODO: Not every function should be unregistered after a single call.
                # Maybe we can receive whether to unregister through the callback info
                # somehow.
                s.cb_code += "\tdefer callbackUnregister(uid)\n"
                s.cb_code += f"\t(callbackFn(uid).({param.typ.go_str()}))("
                for j, p in enumerate(step_st.values):
                    if j != 0:
                        s.cb_code += ", "
                    s.cb_code += p.name
                s.cb_code += ")\n"
                s.cb_code += "}\n"
                s.code += "var callback_uid unsafe.Pointer\n"
                s.code += "var callback *[0]byte\n"
                s.code += f"if {param.name} != nil {{\n"
                s.code += f"\tcallback_uid = unsafe.Pointer(uintptr(callbackRegister({param.name})))\n"
                s.code += f"\tcallback = (*[0]byte)(C.{cb_name})\n"
                s.code += "}\n"
                new_values.append(Var("callback", param.typ))
            elif param.name == "user_data":
                s.in_params = [x for x in s.in_params if x.name != "user_data"]
                new_values.append(Var("callback_uid", param.typ))
            else:
                name = s.mkvar(param.name)
                s.code += f"{name} := {param.typ.conv_from_go(param.name)}\n"
                new_values.append(Var(name, param.typ))
        s.values = new_values

class FunctionStepConvToGo(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        new_values = []
        for i, param in enumerate(s.values):
            if param.typ.gobasetyp == "":
                # Already Go-only type
                new_values.append(param)
                continue
            name = s.mkvar(param.name)
            s.code += f"{name} := {param.typ.conv_to_go(param.name)}\n"
            new_values.append(Var(name, param.typ))
        s.values = new_values

#class FunctionStepGeneric(FunctionStep):
#    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
#        in_names = [p.name for p in s.in_params]
#        if not ("host_ptr" in in_names and "size" in in_names):
#            return
#        s.generic += "E comparable, S ~[]E"

@dataclass
class SliceHint:
    data_ptr_name: str
    data_len_name: str|None = None # Assuming zero-terminated if None
    actual_len_name: str|None = None # Slice is returned if not None
    data_count_name: str|None = None
    kind: str = "array" # array|bytes|string|bytearr|stringarr

SLICE_HINTS = {
    "clGetPlatformIDs": [SliceHint("platforms", "num_entries", "num_platforms")],
    "clGetDeviceIDs": [SliceHint("devices", "num_entries", "num_devices")],
    "clCreateSubDevice": [SliceHint("out_devices", "num_devices", "num_devices_ret"), SliceHint("properties")],
    "clCreateContext": [SliceHint("devices", "num_devices"), SliceHint("properties")],
    "clCreateContextFromType": [SliceHint("properties")],
    "clGetSupportedImageFormats": [SliceHint("image_formats", "num_entries", "num_image_formats")],
    "clCreateProgramWithSource": [SliceHint("strings", "lengths", data_count_name="count", kind="stringarr")],
    "clCreateProgramWithBinary": [SliceHint("device_list", "num_devices")],
    "clCreateProgramWithBuiltInKernels": [SliceHint("device_list", "num_devices")],
    "clBuildProgram": [SliceHint("device_list", "num_devices")],
    "clCompileProgram": [SliceHint("device_list", "num_devices")],
    "clLinkProgram": [SliceHint("device_list", "num_devices")],
    "clCreateKernel": [SliceHint("kernel_name", kind="string")],
    "clCreateKernelsInProgram": [SliceHint("kernels", "num_kernels", "num_kernels_ret")],
    "clWaitForEvents": [SliceHint("event_list", "num_events")],
    "clEnqueueReadBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueReadBufferRect": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueWriteBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueWriteBufferRect": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueFillBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueCopyBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueCopyBufferRect": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueReadImage": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueWriteImage": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueFillImage": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueCopyImage": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueCopyImageToBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueMapToBuffer": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueMapImage": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueUnmapMemObject": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueMigrateMemObjects": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueNDRangeKernel": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueNativeKernel": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueMarkerWithWaitList": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueBarrierWithWaitList": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMFree": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMMemcpy": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMMemFill": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMMap": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMUnmap": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueSVMMigrateMem": [SliceHint("event_wait_list", "num_events_in_wait_list")],
    "clEnqueueTask": [SliceHint("event_wait_list", "num_events_in_wait_list")],
}

class FunctionStepSlice(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        if not func.name in SLICE_HINTS:
            return
        for hint in SLICE_HINTS[func.name]:
            val_names = [p.name for p in s.values]
            if hint.data_len_name is not None:
                if hint.data_len_name not in val_names:
                    raise Exception(f"cannot find {hint.data_len_name} in {func.name}")
                data_len_idx = val_names.index(hint.data_len_name)
            if hint.data_ptr_name not in val_names:
                raise Exception(f"cannot find {hint.data_ptr_name} in {func.name}")
            data_ptr_idx = val_names.index(hint.data_ptr_name)
            if hint.kind == "array" and hint.actual_len_name is None:
                slc_name = s.values[data_ptr_idx].name
                data_ptr_typ = s.values[data_ptr_idx].typ
                if hint.data_len_name is not None:
                    data_len_name = s.values[data_len_idx].name
                    data_len_typ = s.values[data_len_idx].typ
                    len_name = s.mkvar("dlen")
                    s.code += f"{len_name} := {data_len_typ.conv_from_go(f"len({slc_name})")}\n"
                else:
                    elem_zero_name = s.mkvar("elem_zero")
                    slc2_name = s.mkvar("slc")
                    s.code += f"var {elem_zero_name} {data_ptr_typ.gobasetyp}\n"
                    s.code += f"if len({slc_name}) > 0 {{\n"
                    s.code += f"\t{slc_name} = append(slices.Clone({slc_name}), {elem_zero_name})\n"
                    s.code += "}\n"
                ptr_name = s.mkvar("dptr")
                s.code += f"var {ptr_name} {data_ptr_typ.cgo_str()}\n"
                s.code += f"if len({slc_name}) > 0 {{\n"
                s.code += f"\t{ptr_name} = {data_ptr_typ.conv_from_go(f"unsafe.Pointer(&{slc_name}[0])")}\n"
                s.code += "}\n"
                s.code += f"defer runtime.KeepAlive({slc_name})\n"
                s.values[data_ptr_idx] = Var(ptr_name, Type(data_ptr_typ.cbasetyp, "", ptrlvl=data_ptr_typ.ptrlvl))
                slc = Var(slc_name, Type("", data_ptr_typ.gobasetyp, goslice=True))
                if hint.data_len_name is not None:
                    s.values[data_len_idx] = Var(len_name, Type(data_len_typ.cbasetyp, ""))
                    hi, lo = max(data_len_idx, data_ptr_idx), min(data_len_idx, data_ptr_idx)
                    s.in_params[lo] = slc
                    s.in_params.pop(hi)
                else:
                    s.in_params[data_ptr_idx] = slc
            elif hint.kind == "string":
                data_ptr_name = s.values[data_ptr_idx].name
                data_name = s.mkvar("dptr")
                fin_name = s.mkvar("dfin")
                s.code += f"{data_name}, {fin_name} := stringToC({data_ptr_name})\n"
                s.code += f"defer {fin_name}()\n"
                s.values[data_ptr_idx] = Var(data_name, Type("char", "", ptrlvl=1))
                s.in_params[data_ptr_idx] = Var(data_ptr_name, Type("", "string"))
            elif hint.kind == "stringarr":
                data_count_idx = val_names.index(hint.data_count_name)
                data_ptr_name = s.values[data_ptr_idx].name
                data_name = s.mkvar("dptr")
                lens_name = s.mkvar("dlens")
                count_name = s.mkvar("dcnt")
                fin_name = s.mkvar("dfin")
                s.code += f"{data_name}, {lens_name}, {fin_name} := stringsToC({data_ptr_name})\n"
                s.code += f"{count_name} := C.cl_uint(len({data_ptr_name}))\n"
                s.code += f"defer {fin_name}()\n"
                s.values[data_count_idx] = Var(count_name, Type("cl_uint", ""))
                s.values[data_ptr_idx] = Var(data_name, Type("char", "", ptrlvl=2))
                s.values[data_len_idx] = Var(lens_name, Type("size_t", "", ptrlvl=1))
                s.in_params[data_ptr_idx] = Var(data_ptr_name, Type("", "string", goslice=True))
                s.in_params.pop(data_len_idx)
                s.in_params.pop(data_count_idx)
            else:
                actual_len_idx = val_names.index(hint.actual_len_name)
        #in_names = [p.name for p in s.in_params]
        #if not ("host_ptr" in in_names and "size" in in_names):
        #    return
        #s.generic += "E comparable, S ~[]E"

class FunctionStepCall(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        if len(s.out_params) > 0:
            retname = s.mkvar("res")
            s.code += f"{retname} := "
        s.code += f"C.{func.name}("
        for i, param in enumerate(s.values):
            if i != 0:
                s.code += ", "
            s.code += param.name
        s.code += ")\n"
        s.values = []
        if len(s.out_params) > 0:
            s.values.append(Var(retname, s.out_params[0].typ))

class FunctionStepErrorPreCall(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        in_names = [p.name for p in s.in_params]
        if "errcode_ret" in in_names:
            ec_idx = in_names.index("errcode_ret")
            s.in_params.pop(ec_idx)
            s.code += "var errCode C.cl_int\n"
            ec_v_idx = [v.name for v in s.values].index("errcode_ret")
            s.values[ec_v_idx] = Var("&errCode", Type("cl_int", "", ptrlvl=1))

class FunctionStepErrorPostCall(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        in_names = [p.name for p in func.typ.func_params]
        if "errcode_ret" in in_names:
            err = s.mkvar("err")
            s.code += f"{err} := makeError(ErrorCode(errCode))\n"
            s.out_params.append(Var("_", Type("", "error")))
            s.values.append(Var(err, Type("", "error")))
        elif len(s.out_params) >= 1 and s.out_params[0].typ.cbasetyp == "cl_int":
            err = s.mkvar("err")
            s.code += f"{err} := makeError(ErrorCode({s.values[0].name}))\n"
            s.out_params[0] = Var("_", Type("", "error"))
            s.values[0] = Var(err, Type("", "error"))

class FunctionStepRet(FunctionStep):
    def __call__(self, s: FunctionStepState, ctx: Context, func: Function):
        if len(s.values) == 0:
            return
        s.code += "return "
        for i, param in enumerate(s.values):
            if i != 0:
                s.code += ", "
            s.code += param.name
        s.code += "\n"
        s.values = []

def generate_bindings(dstfile: str, go_prelude: str, headers: list[str]) -> None:
    with open(dstfile, "w") as o, open(dstfile+".h", "w") as o_c:
        ctx = Context()

        ctx.add(make_simple_type("char", "int8"))
        ctx.add(make_simple_type("uchar", "uint8"))
        ctx.add(make_simple_type("size_t", "uint64"))
        ctx.add(make_simple_type("cl_bool", "bool"))
        ctx.add(make_simple_type("cl_char", "int8"))
        ctx.add(make_simple_type("cl_uchar", "uint8"))
        ctx.add(make_simple_type("cl_short", "int16"))
        ctx.add(make_simple_type("cl_ushort", "uint16"))
        ctx.add(make_simple_type("cl_int", "int32"))
        ctx.add(make_simple_type("cl_uint", "uint32"))
        ctx.add(make_simple_type("cl_long", "int64"))
        ctx.add(make_simple_type("cl_ulong", "uint64"))
        ctx.add(make_simple_type("cl_half", "float16.Float16"))
        ctx.add(make_simple_type("cl_float", "float32"))
        ctx.add(make_simple_type("cl_double", "float64"))
        ctx.add(make_simple_type("void", "void"))

        def docs_url(typ: str) -> str:
            return f"https://registry.khronos.org/OpenCL/specs/unified/refpages/man/html/{typ}.html"

        o.write(go_prelude)
        for header in headers:
            o.write(f"// BEGIN {dstfile} //\n\n")
            hdr = ""
            with open(header) as f:
                hdr = f.read()

            o.write("// Typedefs\n\n")
            typedefs = [m["name"] for m in
                re.finditer(r"^typedef [^\n{}]+ (?P<name>cl_[a-z0-9_]+);", hdr, re.MULTILINE)]
            for name in typedefs:
                if name in ctx.typs:
                    continue
                ctx.add(make_simple_type(name))
                o.write(f"// See {docs_url(name)}\n")
                o.write(f"type {ctx.typs[name].go_str()} {ctx.typs[name].cgo_str()}\n")
            o.write("\n")

            o.write("// Structs\n\n")
            structs = [Struct(ctx, m["name"], m["body"]) for m in
                re.finditer(r"^typedef struct[^{\n]*\{(?P<body>(\n[ #][^\n]+)+\n)\} *(?P<name>cl_\w+);", hdr, re.MULTILINE)]
            for struct in structs:
                name = struct.name
                ctx.add(make_simple_type(name))
                o.write(f"// See {docs_url(name)}\n")
                o.write(f"type {ctx.typs[name].go_str()} {ctx.typs[name].cgo_str()}\n")
                for field in struct.fields:
                    fname = snake_to_camel(field.name)
                    o.write(f"func (s *{ctx.typs[name].go_str()}) {fname}() {field.typ.go_str()} {{")
                    o.write(f" return {field.typ.conv_to_go(f"s.{field.name}")} ")
                    o.write(f"}}\n")
                    o.write(f"func (s *{ctx.typs[name].go_str()}) Set{fname}(v {field.typ.go_str()}) {{")
                    o.write(f" s.{field.name} = {field.typ.conv_from_go("v")} ")
                    o.write(f"}}\n")
            o.write("\n")

            if os.path.basename(header) == "cl.h":
                o.write("// Enums\n\n")
                enums = []
                enums.append(Enum(
                        "int",
                        re.search(r"^\/\* Error Codes \*\/\n(?P<body>(.+\n\n?)+)", hdr, re.MULTILINE)["body"],
                        gotyp="ErrorCode",
                    ))
                for m in re.finditer(r"^\/\* (?P<type>cl_\w+)( and (?P<type2>cl_\w+))?( - bitfield)? \*\/\n(?P<body>([^\n].*\n)+)", hdr, re.MULTILINE):
                    ctyp = m["type"]
                    gotyp = ""
                    if ctyp in ctx.typs:
                        gotyp = ctx.typs[ctyp].go_str()
                    else:
                        gotyp = snake_to_camel(ctyp.removeprefix("cl_"))
                    enums.append(Enum(ctyp, m["body"], gotyp))
                for enum in enums:
                    o.write(f"// See {docs_url("enums")}\n")
                    o.write(f"const ( // {enum.gotyp}\n")
                    for value in enum.values:
                        o.write(f"\t{value[0]} {enum.gotyp} = {value[1]}\n")
                    o.write(f")\n")

                for enum in enums:
                    if enum.ctyp in ("cl_version", "cl_bool"):
                        continue
                    o.write(f"func (v {enum.gotyp}) String() string {{\n")
                    o.write("\tswitch v {\n")
                    for value in enum.values:
                        if "/* deprecated */" in value[1]:
                            # Some enum values have been renamed with the
                            # old name marked as deprecated; we want to avoid
                            # duplicates
                            continue
                        o.write(f"\tcase {value[0]}: return \"{value[0]}\"\n")
                    o.write(f"\tdefault: return fmt.Sprintf(\"UNKNOWN (%d)\", v)\n")
                    o.write(f"\t}}\n")
                    o.write(f"}}\n")
                o.write("\n")

                o.write("// Functions\n\n")
                funcs = [Function(ctx, m["name"], m["type"], m["params"], m["api_version"]) for m in
                    re.finditer(r"^extern CL_API_ENTRY (CL_API_PREFIX__\w+ )?(?P<type>[\w \*]+) CL_API_CALL\n(?P<name>cl\w+)\((?P<params>(.+,\n)*.+)\) CL_API_SUFFIX__(?P<api_version>\w+);", hdr, re.MULTILINE)]
                for func in funcs:
                    if func.name == "clEnqueueNativeKernel":
                        # TODO This function handles callbacks a bit strangely
                        continue
                        #func.typ.func_params[2].name = "user_data"
                        #func.typ.func_params[1].typ.func_params = [Var("user_data", Type("void", "void", ptrlvl=1))]

                    steps = [
                        #FunctionStepNumEntries(),
                        FunctionStepSlice(),
                        FunctionStepErrorPreCall(),
                        FunctionStepConvToC(),
                        FunctionStepCall(),
                        FunctionStepErrorPostCall(),
                        FunctionStepConvToGo(),
                        FunctionStepRet(),
                    ]
                    step_st = FunctionStepState(func.typ.func_params, [Var("_", func.typ.func_results[0].typ)] if len(func.typ.func_results) > 0 else [])
                    for step in steps:
                        step(step_st, ctx, func)

                    o_c.write(step_st.c_code)
                    o.write(step_st.cb_code)

                    goname = func.name.removeprefix("cl")
                    o.write(f"// See {docs_url(func.name)}\n")
                    o.write(f"func {goname}")
                    if step_st.generic != "":
                        o.write(f"[{step_st.generic}]")
                    o.write("(")
                    for i, param in enumerate(step_st.in_params):
                        if i != 0:
                            o.write(", ")
                        o.write(param.go_str())
                    o.write(") ")
                    if len(step_st.out_params):
                        o.write("(")
                        for i, param in enumerate(step_st.out_params):
                            if i != 0:
                                o.write(", ")
                            o.write(param.go_str())
                        o.write(") ")
                    o.write("{\n")
                    o.write(textwrap.indent(step_st.code, "\t"))
                    o.write("}\n")
                o.write("\n")

            o.write(f"// END {dstfile} //\n\n")

if __name__ == "__main__":
    if not os.path.isdir("cl-3.1"):
        extract_c_source_from_zip_url(
            "cl-3.1",
            OPENCL_ICD_LOADER_ZIP_URL,
            OPENCL_ICD_LOADER_INCLUDE_RE,
            exclude_re = OPENCL_ICD_LOADER_EXCLUDE_RE,
            preludes = OPENCL_ICD_LOADER_PRELUDES,
            extra_files = OPENCL_ICD_LOADER_EXTRA_FILES,
        )
        extract_c_source_from_zip_url(
            "cl-3.1/inc/CL",
            OPENCL_HEADERS_ZIP_URL,
            OPENCL_HEADERS_INCLUDE_RE,
            replacements = OPENCL_HEADERS_REPLACEMENTS,
        )
    generate_bindings(
        "cl-3.1/cl.go",
        GO_PRELUDE,
        [
            "cl-3.1/inc/CL/cl_platform.h",
            "cl-3.1/inc/CL/cl.h",
        ],
    )